rules:
  class-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0
  no-ids: 0
  force-element-nesting: 0
  nesting-depth: 3
  no-important: 0
  no-color-literals: 0
  leading-zero: 0
  force-pseudo-nesting: 0
  quotes:
    - 1
    - style: double